project:
  type: website
  output-dir: docs

website:
  title: "CTRL+R Takımı Analitik Labı"
  navbar:
    search: true
    left:
      - text: Ana Sayfa
        href: index.qmd
      - text: Takım Üyeleri
        href: takim.qmd
      - text: Portfolyo
        href: portfolyo.qmd
      - text: Proje
        href: proje.qmd


            
    tools:
      - icon: github
        href: https://github.com

  sidebar:
    - title: "Çalışmalar"
      style: "docked"
      search: true
      contents:
        - portfolyo.qmd
        - portfolyo/calisma1.qmd
        - portfolyo/calisma2.qmd  
        
    - title: "Takım"
      style: "docked"
      search: true
      contents:
        - takim.qmd
        - takim/servetmerickursad.qmd
        - takim/ekin.qmd
        - takim/sefa.qmd  
        - takim/feyza.qmd  
        - takim/ozge.qmd  
        - takim/mehmet.qmd

  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    center: "EMU Hacettepe MUY665 - 2024-2025 Bahar" 
    border: true
format:
  html:
    code-fold: false
    toc: true
    toc-location: left
    theme: 
      light: simplex 
      dark: cyborg
    css: styles.css


editor: visual

