---
title: "Takım: Ctrl + R"
sidebar: false 
---

MUY660-İş Analitiği dersi takım sayfamıza hoş geldiniz.

Bu analitik çalışmalarımızı paylaşıyoruz.

Lütfen faaliyetlerimizi görmek için için bizi takipte kalın.

## Takım Üyeleri

1.  [Servet Meriç Kürşad](/takim/servetmerickursad.qmd)

2.  [Ekin Uzunhasanoğlu Sarıgül](/takim/ekin.qmd)

3.  [Sefa Çelik](/takim/sefa.qmd)

4.  [Feyza Dönmez Bozok](/takim/feyza.qmd)

5.  [Özge Avşar](/takim/ozge.qmd)

6.  [Mehmet Gençağa](/takim/mehmet.qmd)


## Proje Adı

MUY660-İş Analitiği iyileştirme çalışmaları (örnek)

## Proje Konusu

Örnek: Bu projede MUY660-İş Analitiği ders içeriğinin analitik yaklaşımlarla iyileştirilmesini hedefledik. Bu doğrultuda tüm üniversitelerdeki benzer derslerin verisini toplayarak bir veri seti oluşturduk Analiz için ........ yöntemleri kullanarak, ....... çalışmaları yaptık Sonuç olarak, MUY660-İş Analitiği dersinin dünyadaki tüm derslerden daha iyi olduğunu ve bu dersi aldığımız için çok mutlu olduğumuzu tespit ettik.

## Veri Seti Hakkında Özet Bilgi

## Sonuçlar
Burada key takeways verilmelidir. En az 3 en fazla 5 madde ile çarpıcı sonuçlar sunulmalıdır.
