---
title: "Çalışma 2"
---

Projemizde yaptığımız veri analizinin kodlarını aşağıda görebilirsiniz;


library(tidyverse)
library(dslabs)
library(dplyr)
bosanma_long <- tbl_bosanma %>%
  pivot_longer(-Province_name, names_to = "years", values_to = "bosanma_sayisi")
bosanma_sirali<-arrange(bosanma_long,years)
bosanma_sirali<-bosanma_sirali|>relocate(years,.before=Province_name)
bosanma_son<-filter(bosanma_sirali,years>=2008,years<2024)
bosanma_son$years<-as.numeric(bosanma_son$years)
toplu_tablo1 <- left_join(tbl_egitim, bosanma_son, by = c("years" = "years", "Province_name" = "Province_name"))
medeni_yeni<-select(tbl_medeni,"Year","Province","Married-Total","Divorced-Total")
medeni_yeni<-arrange(medeni_yeni,Year)                              
medeni_son<-filter(medeni_yeni,Year<2024)
medeni_son$Year<-as.numeric(medeni_son$Year)
toplu_tablo<-left_join(toplu_tablo1, medeni_son, by = c("years" = "Year", "Province_name" = "Province"))
toplu_tablo<-filter(toplu_tablo,years>=2018)
egitim_orani<-toplu_tablo %>%
  group_by(years) %>%
  summarise(across(c("General_Total-Total", "Primary_school-Total","Lower_secondary_school-Total","Upper_secondary_school-Total","Universities_and_other_higher_educational_institutions-Total","Master_(Including_5_or_6_Years_Faculties)-Total","Doctorate-Total"), ~ sum(.x, na.rm = TRUE)))
egitim_orani <- egitim_orani %>%
  mutate(
    egitim = 
      `Primary_school-Total` +
      `Lower_secondary_school-Total` +
      `Upper_secondary_school-Total` +
      `Universities_and_other_higher_educational_institutions-Total` +
      `Master_(Including_5_or_6_Years_Faculties)-Total` +
      `Doctorate-Total`
  )
egitim_orani <- egitim_orani %>%
  mutate(egitim_orani = egitim/`General_Total-Total`  )
toplu_tablo<-toplu_tablo %>%
  mutate(Illiterate_rate=`Illiterate-Total`/`General_Total-Total`
           )
toplu_tablo<-toplu_tablo %>%
  mutate(higher_edu=`Universities_and_other_higher_educational_institutions-Total`+`Master_(Including_5_or_6_Years_Faculties)-Total`+`Doctorate-Total`
  )
toplu_tablo<-toplu_tablo %>%
  mutate(higher_edu_rate=higher_edu/`General_Total-Total`
  )
toplu_tablo<-toplu_tablo %>%
  mutate(divorce_rate=`Divorced-Total`/`General_Total-Total`
  )

```

